### ISSUE TITLE
Fabric/Threadbare inconsistency: UnicodeDecodeError

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/threadbare#30]
```python
bldr switch_revision_update_instance:search--continuumtest,approved
...
54.221.28.185   out: Collecting pip
54.221.28.185   out:   Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce1
4b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
exception while executing task 'switch_revision_update_instance': 'ascii' codec can't encode character u'\u258e' in position 10
: ordinal not in range(128)

Traceback (most recent call last):
  File "src/taskrunner.py", line 218, in exec_task
    return_map['result'] = task_map['fn'](*task_args, **task_kwargs)
  File "/home/giorgio/code/builder/src/decorators.py", line 80, in call
    return func(stackname, *args, **kwargs)
  File "/home/giorgio/code/builder/src/deploy.py", line 18, in switch_revision_update_instance
    bootstrap.update_stack(stackname, service_list=['ec2'], concurrency=concurrency_for(stackname, concurrency))
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 398, in update_stack
    fn(stackname, context, **actual_arguments)
  File "/home/giorgio/code/builder/src/buildercore/context_handler.py", line 84, in decorated_with_only_if
    return fn(stackname, context, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/decorators.py", line 18, in _wrapper
    return func(stackname, *args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 549, in update_ec2_stack
    stack_all_ec2_nodes(stackname, _update_ec2_node, username=BOOTSTRAP_USER, concurrency=concurrency)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 370, in stack_all_ec2_nodes
    return serial_work(single_node_work, params)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 382, in serial_work
    return execute(serial(single_node_work), hosts=list(params['public_ips'].values()))
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 222, in execute_with_hosts
    results = execute(func, param_key="host_string", param_values=host_list)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 202, in execute
    return _serial_execution(func, param_key, param_values)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 151, in _serial_execution
    result_list.append(func())
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 15, in inner
    return func(*args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 343, in single_node_work
    return workfn(**work_kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 508, in _update_ec2_node
    run_script('bootstrap.sh', salt_version, minion_id, install_master_flag, master_ip, **environment_vars)
  File "/home/giorgio/code/builder/venv/local/lib/python2.7/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 54, in run_script
    result = remote_sudo(" ".join(env_string + cmd))
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 371, in remote_sudo
    return remote(command, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 331, in remote
    stdout = _process_output(sys.stdout, result["stdout"], **output_kwargs)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 250, in _process_output
    new_results = [_print_line(output_pipe, line, **kwargs) for line in result_list]
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 237, in _print_line
    output_pipe.write(template.format(**template_kwargs))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u258e' in position 10: ordinal not in range(128)
```

**Comment by lsh-0** [comment]
fix: https://github.com/elifesciences/threadbare/pull/31
